### ISSUE TITLE
minor bug with targeting border

### ISSUE THREAD

**Issue by klepp0906** [int3ro/Nameplates_Threat#29] opened 2022-12-19 20:56 UTC
seems if you disable "color out of combat" (which i do as i prefer the default blizzard colors for out of combat mobs and that seems like the ideal way to do so while keeping threat coloring) then the white border you get when targeting mobs does not persist.

it will display for a brief second when initially targeting a mob, then disappear.  if the mob is in combat, it persists however.

**Comment by mikfhan** [comment] 2022-12-21 06:16
Oh! yeah it colors border black when resetFrame is called after combat ends, should be fixed now if you want to try it out :)

https://github.com/int3ro/Nameplates_Threat/raw/mikfhan/NamePlatesThreat.lua

Just download/save the file above, overriding your current NamePlatesThreat.lua - it's for the upcoming 10.0.5 patch.

**Comment by klepp0906** [comment] 2022-12-21 10:57
> y for a brief second when initially targeting a mob, then disappear. if the mob is in combat, it persists ho

will give it a go today, thank you for the fix! (and addon!)

**Comment by mikfhan** [comment] 2023-01-20 06:45
Sounds like the issue is fixed :) will deploy 3.5-release next week at the weekly reset when Retail 10.0.5 patch arrives.

**Closed** 2023-01-28 17:44 UTC
Labels: bug
